### ISSUE TITLE
Criar tabela de servidores para o balanceador

### ISSUE THREAD

**Issue by RicardoBC** [pablohenrique/scarlet#11]
O balanceador terá uma tabela com os servidores e o intervalo de dados de cada servidor. Tratar para atualizar a tabela quando um novo servidor for instanciado, atualizando esta tabela.

**Comment by pablohenrique** [comment]
Map(Server,0..249)

0, 1, 2 = row

MD5(PK,ROW) -> 

Cliente -> Req -> Balancer -> Find Servidor -> Map(S,I) -> Process -> Response -> Done

**Comment by pablohenrique** [comment]
```ruby
@intervalo = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,x,y,z]
@bancos  = [b1, b2, b3, b4]

@banco.new('endereco', 'porta')
@usando_o_banco = TCPServer.new('endereco', 'porta')

Mapa = {
  "chave" => "valor"
  "0" => ['endereco', 'porta_0'],
  "1" => ['endereco', 'porta_0'],
  "2" => ['endereco', 'porta_1'],
  "3" => ['http://scarlet.aws.com', 80]
}
```

class DatabaseManager: Deve criar e gerenciar o mapa de intervalo/banco. Exemplo: create_map ( "address,port"[ ] ) void 

Deve retornar qual e o banco que um dado possa estar (ou seja, endereco e porta). Exemplo: get_database( Hash_MD5_do_usuario ) return ['endereco', 'porta']

Deve gerenciar a elasticidade/contracao do mapa.
