### ISSUE TITLE
Banco de dados - Estrutura

### ISSUE THREAD

**Issue by pablohenrique** [pablohenrique/scarlet#14]
Vamos usar pastas! E dentro das pastas teremos arquivos. O nosso intervalo e esse:
```ruby
@interval = [0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,x,y,z]
```
Cada elemento do intervalo sera o nome de uma pasta. So teremos uma unica tabela no nosso sistema, que sera representada pela classe Usuario.rb. Os arquivos contidos em cada pastas serao nomeados de acordo com o Hash MD5 do nome ou email do usuario (exemplo: 7e4b64eb65e34fdfad79e623c44abd94.json) e neste contera a estrutura da issue #13 .

Como funciona:

POST User@Class localhost:8889 -> Hash=MD5.hash(User@Class.email) -> getServerOnInterval(Hash@MD5.getFirstChar) -> open folder -> save User.to_json as Hash@MD5.json

O cliente faz um post ao balanceador passando um objeto (ou campos) que representa um usuario (veja issue #13). O balanceador usa o email do usuario numa funcao Hash (MD5). O retorno da funcao Hash sera usado para descobrir em qual servidor guardaremos a informacao (pegando o primeiro caracter do Hash) e tambem sera usado para nomear o arquivo com os dados do usuario. Depois que o servidor e encontrado, encaminharemos ate a pasta que e indicada pelo intervalo e criaremos um arquivo usando o Hash. Esse arquivo deve conter os dados do usuarios, que podem ser vistos na issue #13.

O que voces acham?

**Comment by RicardoBC** [comment]
Correto!
